config/routes.rb
UpgSequences::Application.routes.draw do
  namespace :admin do
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'paid_unpaid/:id', :to => 'sequence_requests#paid_unpaid', :as => 'paid_unpaid'
    match 'cancel/:id', :to => 'sequence_requests#cancel', :as => 'cancel'
    match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
    match 'download_file', :to => 'sequence_requests#download_file', :as => 'download_file'
    match 'send_results/:id', :to => 'sequence_requests#send_results', :as => 'send_results'
    match 'generate_and_download_xls', :to => 'sequence_requests#generate_and_download_xls', :as => 'generate_and_download_xls'
    match 'reports_by_ur', :to => 'sequence_requests#reports_by_ur', :as => 'reports_by_ur'
    post 'generate_reports_by_ur', :to => 'sequence_requests#generate_reports_by_ur', :as => 'generate_reports_by_ur'
    post 'search_by_folio', :to => 'sequence_requests#search_by_folio', :as => 'search_by_folio'
    resources :user_sessions, :users, :sequence_requests,:prices
  end

  resources :sequence_requests

  match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
  match 'sequence_request_sent', :to => 'sequence_requests#sent', :as => 'sequence_request_sent'
  match 'sequence_request_download_file', :to => 'sequence_requests#download_file', :as => 'sequence_request_download_file'

  root :to => "sequence_requests#new"

end

app/models/admin/price.rb
class Admin::Price < ActiveRecord::Base
  validates :price, :numericality => {:greater_than => 0}
end

app/controllers/admin/prices_controller.rb
class Admin::PricesController < ApplicationController
  # GET /admin/prices
  # GET /admin/prices.xml
  before_filter :authorize
  layout 'application'

  def index
    @admin_prices = Admin::Price.all

    respond_to do |format|
      format.html # idx.back.erb
      format.xml  { render :xml => @admin_prices }
    end
  end

  # GET /admin/prices/1
  # GET /admin/prices/1.xml
  def show
    @admin_price = Admin::Price.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_price }
    end
  end

  # GET /admin/prices/new
  # GET /admin/prices/new.xml
  def new
    @admin_price = Admin::Price.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_price }
    end
  end

  # GET /admin/prices/1/edit
  def edit
    @admin_price = Admin::Price.find(params[:id])
  end

  # POST /admin/prices
  # POST /admin/prices.xml
  def create
    @admin_price = Admin::Price.new(params[:admin_price])

    respond_to do |format|
      if @admin_price.save
        format.html { redirect_to(@admin_price, :notice => 'Price was successfully created.') }
        format.xml  { render :xml => @admin_price, :status => :created, :location => @admin_price }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/prices/1
  # PUT /admin/prices/1.xml
  def update
    @admin_price = Admin::Price.find(params[:id])

    respond_to do |format|
      if @admin_price.update_attributes(params[:admin_price])
        format.html { redirect_to(:action => 'index', :notice => 'Price was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/prices/1
  # DELETE /admin/prices/1.xml
  def destroy
    @admin_price = Admin::Price.find(params[:id])
    @admin_price.destroy

    respond_to do |format|
      format.html { redirect_to(admin_prices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/prices_helper.rb
module Admin::PricesHelper
end

app/views/admin/prices/_form.html.haml
= form_for(@admin_price) do |f|
  - if @admin_price.errors.any?
    #error_explanation
      %h2
        = "#{@admin_price.errors.count} #{t(:error)} El precio no ha sido modificado."
      %ul
        - @admin_price.errors.full_messages.each do |msg|
          %li= msg

  .span-19.tbl-header-top
    .span-8
      = f.label :description
    .span-2.last
      = f.label :price

  .span-19.tbl-det
    .span-8
      = f.text_field :description, :style => "width: 308px; border: none;", :disabled => :true
    .span-2
      = f.text_field :price, :style => "width: 68px; text-align: right;"
    .span-1
      &nbsp
    .span-8.last
      = f.submit  t(".submit"), :class => 'jq-button'
      = link_to t('crud.back'), admin_prices_path,  :class => 'jq-button'

app/views/admin/prices/edit.html.haml
%br/
%h1=t('prices.price')
= render 'form'

app/views/admin/prices/index.html.haml
%br/
%h1= t('prices.prices')

.span-16.last.tbl-header-top
  .span-10
    %label=t('prices.description')
  .span-2
    %label=t('prices.price')
  .span-1.last
    &nbsp

.span-16.last.tbl-det
  - @admin_prices.each do |admin_price|
    .span-10
      = admin_price.description
    .span-2{:style => "text-align: right;"}
      =number_to_currency admin_price.price
    .span-1.last.tbl-det-center
      = link_to '', edit_admin_price_path(admin_price), :class => 'icon-set-edit jq-button', :title => "Modificar precio"

app/views/admin/prices/new.html.haml
%br/
%h1 New admin_price
= render 'form'
= link_to 'Back', admin_prices_path

app/views/admin/prices/show.html.haml
%p#notice= notice
%p
  %b Description:
  = @admin_price.description
%p
  %b Price:
  = @admin_price.price
%p
  %b User:
  = @admin_price.user_id
= link_to 'Edit', edit_admin_price_path(@admin_price)
|
\#{link_to 'Back', admin_prices_path}