config/routes.rb
UpgSequences::Application.routes.draw do
  namespace :admin do
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'paid_unpaid/:id', :to => 'sequence_requests#paid_unpaid', :as => 'paid_unpaid'
    match 'cancel/:id', :to => 'sequence_requests#cancel', :as => 'cancel'
    match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
    match 'download_file', :to => 'sequence_requests#download_file', :as => 'download_file'
    match 'send_results/:id', :to => 'sequence_requests#send_results', :as => 'send_results'
    match 'generate_and_download_xls', :to => 'sequence_requests#generate_and_download_xls', :as => 'generate_and_download_xls'
    match 'reports_by_ur', :to => 'sequence_requests#reports_by_ur', :as => 'reports_by_ur'
    post 'generate_reports_by_ur', :to => 'sequence_requests#generate_reports_by_ur', :as => 'generate_reports_by_ur'
    post 'search_by_folio', :to => 'sequence_requests#search_by_folio', :as => 'search_by_folio'
    resources :user_sessions, :users, :sequence_requests,:prices
  end

  resources :sequence_requests

  match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
  match 'sequence_request_sent', :to => 'sequence_requests#sent', :as => 'sequence_request_sent'
  match 'sequence_request_download_file', :to => 'sequence_requests#download_file', :as => 'sequence_request_download_file'

  root :to => "sequence_requests#new"

end

app/models/sequence_request.rb
# -*- coding: utf-8 -*-

class SequenceRequest < ActiveRecord::Base
  attr_accessor :upload_file

  has_many :sequence_request_details, :order=>"id ASC"
  belongs_to :ur
  accepts_nested_attributes_for :sequence_request_details, :allow_destroy => true

  validates :company, :petitioner, :email, :payment_method, :presence => true

  scope :by_ur_between, ->(start_date, end_date, ur_id) {where(created_at: (start_date..end_date), ur_id: ur_id, status: 'D-CO')}

  STATUS = {
    'A-LE' => 'Recibida',
    'B-PA' => 'Pagada',
    'C-CA' => 'Cancelada',
    'D-CO' => 'Concluida'}

  PMT_METHOD = {
      1 => 'UR',
      2 => 'Conacyt',
      3 => 'PAPIIT',
      4 => 'Efectivo',
      5 => 'Depósito bancario'
  }

  def folio_number
    return Time.now
  end

  before_save :set_folio_and_status

  def set_folio_and_status
    if  self.folio == nil
      self.folio = folio_number
    end
    if self.status == nil
      self.status=STATUS.key('Recibida')
      self.status_change_at=Time.now
    end
  end

  def paid_unpaid
     if self.status ==  STATUS.key('Recibida')
       self.update_attribute :status, STATUS.key('Pagada')
     elsif self.status ==  STATUS.key('Pagada')
       self.update_attribute :status, STATUS.key('Recibida')
     end
  end

  def set_sent_status
     self.update_attribute :status, STATUS.key('Concluida')
     self.update_attribute :status_change_at, Time.now
  end

  def cancel
     self.update_attribute :status, STATUS.key('Cancelada')
  end

  def seq_count
    self.sequence_request_details.count
  end

  def amount
    if self.inb_member then
      self.sequence_request_details.count * Admin::Price.find(2).price
    else
      self.sequence_request_details.count * Admin::Price.find(1).price
    end
  end

  def payment_method_s
    PMT_METHOD[self.payment_method]
  end

  def status_s
    STATUS[self.status]
  end

   #UPLOAD FILE
   #IMPORTANT add to _form view , form_for(@registration_forms, :html => {:multipart => true})
   def upload_file(upload,filename)
      #name =  folio + '_' +upload.original_filename
      directory = "public/results_files"
      # create the file path
      path = File.join(directory, filename)
      # write the file
      File.open(path, "wb") { |f| f.write(upload.tempfile.read) }
   end
end

app/controllers/admin/sequence_requests_controller.rb
# -*- coding: utf-8 -*-

class Admin::SequenceRequestsController < ApplicationController
  before_filter :authorize

  require 'pdf_reporter_results'
  require 'pdf_reporter'
  require 'xls_generator'
  layout 'application'

  def index
    @admin_sequence_requests = SequenceRequest.order("created_at DESC").paginate(:page => params[:page], :per_page => 16)

    respond_to do |format|
      format.html #idx.back.haml                         @admin_sequence_request= SequenceRequest.find(params[:id])

      format.xml { render :xml => @admin_sequence_requests }
    end
  end

  def paid_unpaid
    @admin_sequence_request= SequenceRequest.find(params[:id])
    @admin_sequence_request.paid_unpaid
    redirect_to :action => 'index'
  end

  def cancel
    @admin_sequence_request= SequenceRequest.find(params[:id])
    @admin_sequence_request.cancel
    redirect_to :action => 'index'
  end

  def show
    @admin_sequence_request= SequenceRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @admin_sequence_request }
    end
  end

  # GET /sequence_requests/1/edit
  def edit
    @admin_sequence_request= SequenceRequest.find(params[:id])
  end

  # PUT /sequence_requests/1
  # PUT /sequence_requests/1.xml
  def update
    @admin_sequence_request= SequenceRequest.find(params[:id])

    #REMOVE results_file
    if params[:remove_results_file]=='true' then
      @admin_sequence_request.results_file = nil
    end

    #UPLOAD FILE
    @admin_sequence_request.results_file=params[:sequence_request][:upload_file].original_filename unless params[:sequence_request][:upload_file].nil?


    respond_to do |format|
      if @admin_sequence_request.update_attributes(params[:sequence_request])

        #UPLOAD FILE - IMPORTANT add to _form view , form_for(@model, :html => {:multipart => true})
        @admin_sequence_request.upload_file(params[:sequence_request][:upload_file], "#{@admin_sequence_request.folio.to_s}_#{@admin_sequence_request.results_file}") unless params[:sequence_request][:upload_file].nil?

        #GENERATE PDF REQUEST
        pdf_file_name = "public/pdf_files/#{@admin_sequence_request.folio}.pdf"
        generate_pdf_request(pdf_file_name,@admin_sequence_request)

        format.html { redirect_to admin_sequence_request_path(@admin_sequence_request, :notice => 'Sequence request was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @admin_sequence_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  def add_sequence_request_detail

  end

  def reports_by_ur

  end

  def generate_reports_by_ur
    report_params = params[:report]
    start_date = Date.new(report_params['start_date(1i)'].to_i,report_params['start_date(2i)'].to_i,report_params['start_date(3i)'].to_i).beginning_of_day
    end_date = Date.new(report_params['end_date(1i)'].to_i,report_params['end_date(2i)'].to_i,report_params['end_date(3i)'].to_i).beginning_of_day
    ur_id = report_params[:ur_id] == '999' ? 'id > 0' : "id = #{report_params[:ur_id]}"
    urs = Ur.select(:id).where(ur_id).all.map{|v| v[:id]}
    if params[:generate]
      filename = 'public/pdf_files/sequence_reports.pdf'
      pdf_general_report(start_date, end_date, urs, filename)
      send_file filename, filename: "solicitudes_de_#{start_date.strftime('%Y%m%d')}_a_#{end_date.strftime('%Y%m%d')}.pdf", :type => "registration/xls"
    else
      puts 'SENT XXXXXXXXXXXXXXXXXXXXXXXXXX'
    end
  end


  require 'prawn'
  require "prawn/measurement_extensions"
  def pdf_general_report(start_date, end_date,urs, filename)
    # def initialize
    @pdf = Prawn::Document.new(:page_size   => 'LETTER',
                               :left_margin => 0.7.in,
                               :right_margin => 0.4.in,
                               :top_margin => 0.4.in,
                               :bottom_margin => 0.4.in,
                               :page_layout => :portrait,
                               :template => 'public/pdf_templates/sequence_request_reports.pdf')
    # end

    x= 0.05
    y= 9.15

    # FECHA
    @pdf.draw_text Date.today.strftime("%d/%m/%Y"), :at => [(x+6.4).in,y.in]
    y=y-0.3

    # PERIOD
    @pdf.draw_text "del #{I18n.l(start_date, :format => :long)} al #{I18n.l(end_date, :format => :long)}", :at => [(x+0.75).in,y.in]

    # SEQUENCES
    @pdf.move_down 1.75.in
    header = ['FOLIO','FECHA','SOLICITANTE.','CANTIDAD','IMPORTE']

    col_widths = {0 => 0.75.in, 1 => 1.in, 2 => 4.in, 3 => 0.75.in, 4 => 0.9.in}
    @pdf.font_size = 8
    total = 0
    urs.each do |ur|
      seq_req = SequenceRequest.by_ur_between(start_date,end_date,ur)
      if seq_req.size > 0
        @pdf.text Ur.find(ur).name_and_responsible, :size => 14
        data=seq_req.map{|r| [r.folio, I18n.l(r.created_at, :format => :short), r.petitioner, r.seq_count, r.amount]}

        @pdf.table([header] + data, :header => true, :column_widths => col_widths ) do
          row(0).style(:font_style => :bold, :background_color => 'cccccc')
          column(4).style :align => :right
        end

        # SUB-TOTAL
        total_ur = SequenceRequestDetail.by_ur(ur).size * Admin::Price.find(2).price
        total = total + total_ur
        data = [['TOTAL UR:', total_ur]]
        @pdf.table data, :column_widths => {0 => 6.5.in, 1 => 0.9.in} do
          column(0).style :align => :right
          column(1).style :align => :right, :background_color => 'cccccc'
        end

        @pdf.move_down 0.2.in
      end
    end

    # TOTAL
    data = [['TOTAL:', total]]
    @pdf.table data, :column_widths => {0 => 6.5.in, 1 => 0.9.in} do
      row(0).style(:font_style => :bold, :background_color => 'cccccc')
      column(0).style :align => :right
      column(1).style :align => :right
    end

    @pdf.render_file(filename)

  end

  def send_results
    @admin_sequence_request= SequenceRequest.find(params[:id])

    #GENERATE PDF  RESULTS
    pdf_file_name = "public/pdf_files/#{@admin_sequence_request.folio}_resultados.pdf"
    generate_pdf_results(pdf_file_name, @admin_sequence_request)

    #SENDING MAILS
    admin_emails = Admin::User.select("email").where("follow_requests = ?", true).map(&:email).join ','
    RequestMailer.request_sent_results(@admin_sequence_request.petitioner, @admin_sequence_request.email, admin_emails, @admin_sequence_request.folio, @admin_sequence_request.results_file).deliver

    #CHANGE STATUS
    @admin_sequence_request.set_sent_status
  end

  def generate_pdf_request(file_name,model)
     pdf = PdfReporter.new
     pdf.generate_pdf(file_name, model)
  end

  def generate_pdf_results(file_name, model)
    pdf = PdfReporterResults.new
    pdf.generate_pdf(file_name, model)
  end

  def download_file
     send_file params[:file_name], :type=>"registration/pdf"
  end

  def generate_and_download_xls
    @admin_sequence_request = SequenceRequest.order("created_at DESC")
    file_name =  Time.now.strftime("Solicitudes_de_secuencias_%m%d%Y.xls")
    xls = XlsGenerator.new
    xls.generate_xls(file_name,@admin_sequence_request,'Solicitudes')
    send_file "public/xls_files/#{file_name}", :type => "registration/xls"
  end

end

app/controllers/sequence_requests_controller.rb
# -*- coding: utf-8 -*-

class SequenceRequestsController < ApplicationController
  # GET /sequence_requests
  # GET /sequence_requests.xml

  require 'pdf_reporter'
  layout 'application'

  # GET /sequence_requests/new
  # GET /sequence_requests/new.xml
  def new
    @sequence_request = SequenceRequest.new
    @sequence_request.sequence_request_details.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sequence_request }
    end
  end

  # POST /sequence_requests
  # POST /sequence_requests.xml
  def create
    @sequence_request = SequenceRequest.new(params[:sequence_request])

    #respond_to do |format|
    #  if @sequence_request.save
    #    format.html { redirect_to(@sequence_request, :notice => 'Sequence request was successfully created.') }
    #    format.xml { render :xml => @sequence_request, :status => :created, :location => @sequence_request }
    #  else
    #    format.html { render :action => "new" }
    #    format.xml { render :xml => @sequence_request.errors, :status => :unprocessable_entity }
    #  end
    #end

    respond_to do |format|
      if @sequence_request.save
        #GENERATE PDF
        pdf_file_name = "public/pdf_files/#{@sequence_request.folio}.pdf"
        generate_pdf(pdf_file_name,@sequence_request)

        #SENDING MAILS
        admin_emails = Admin::User.select("email").where("follow_requests = ?", true).map(&:email).join ','
        RequestMailer.request_notification(@sequence_request.petitioner, @sequence_request.email, @sequence_request.folio).deliver
        unless admin_emails.empty?
           RequestMailer.request_notification_admin(@sequence_request.petitioner, admin_emails, @sequence_request.folio).deliver
        end

        msg = "Tu solicitud ha sido enviada correctamente con el folio #{@sequence_request.folio}."

        if @sequence_request.payment_method == 5 then
          RequestMailer.request_notification_bank_deposit('ingresos@inb.unam.mx', @sequence_request.folio).deliver
          msg = msg + ' En breve recibirás vía email la ficha de depósito para que efectúes el pago correspondiente.'
        end

        format.html { redirect_to sequence_request_sent_path(:notice => msg, :file_name => pdf_file_name) }
        format.xml  { render :xml => @sequence_request, :status => :created, :location => @sequence_request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sequence_request.errors, :status => :unprocessable_entity }
      end
    end

  end





  def add_sequence_request_detail

  end

  def generate_pdf(file_name,model)
     pdf = PdfReporter.new
     pdf.generate_pdf(file_name, model)
  end

  def sent
      respond_to do |format|
         format.html
         format.xml  { render :xml => @sequence_request }
      end
   end


  def download_file
     send_file params[:file_name], :type=>"registration/pdf"
  end

=begin
    # GET /sequence_requests/1
  # GET /sequence_requests/1.xml
  def show
    @sequence_request = SequenceRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sequence_request }
    end
  end

   # DELETE /sequence_requests/1
  # DELETE /sequence_requests/1.xml
  def destroy
    @sequence_request = SequenceRequest.find(params[:id])
    @sequence_request.destroy

    respond_to do |format|
      format.html { redirect_to(sequence_requests_url) }
      format.xml  { head :ok }
    end
  end

    # PUT /sequence_requests/1
  # PUT /sequence_requests/1.xml
  def update
    @sequence_request = SequenceRequest.find(params[:id])

    respond_to do |format|
      if @sequence_request.update_attributes(params[:sequence_request])
        format.html { redirect_to(@sequence_request, :notice => 'Sequence request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sequence_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  def index
    @sequence_requests = SequenceRequest.all

    respond_to do |format|
      format.html # index.back.erb
      format.xml  { render :xml => @sequence_requests }
    end
  end

   # GET /sequence_requests/1/edit
  def edit
    @sequence_request = SequenceRequest.find(params[:id])
  end
=end

end

app/helpers/sequence_requests_helper.rb
module SequenceRequestsHelper
end

app/views/sequence_requests/_form.html.haml
= simple_form_for @sequence_request, :html => {:novalidate => true} do |f|
  - if @sequence_request.errors.any?
    #error_explanation
      %h2
        = "#{@sequence_request.errors.count} #{t(:error)} Esta solicitud no ha sido enviada."
      %ul
        - @sequence_request.errors.full_messages.each do |msg|
          %li= msg

  %br/

  .span-24
    .span-12
      =f.input :company, :input_html =>{:style => "width: 450px;"}
    .span-12.last
      =f.input :petitioner, :input_html =>{:style => "width: 450px;"}
    .span-12
      =f.input :email, :input_html =>{:style => "width: 450px;"}
    .span-12.last
      =f.input :phone, :input_html =>{:style => "width: 450px;"}
    .span-12
      =f.input :group_leader, :input_html =>{:style => "width: 450px;"}
    .span-12.last
      .span-12.last
        =f.label :payment_method
      =f.collection_radio_buttons :payment_method, [[1, 'UR'] ,[2, 'Conacyt'], [3, 'PAPIIT'], [4, 'Efectivo'], [5, 'Depósito bancario']], :first, :last
    .span-12
      = f.input :inb_member
    .span-12.last.ur{style: "display: #{@sequence_request.inb_member ? 'inline' : 'none' };"}
      = f.association :ur, label_method: :name_and_responsible, include_blank: false

  %br/

  %h2 Muestras

  =hidden_field_tag 'drc', @drc || 1

  .span-24.tbl-header-top
    .span-12
      =f.label :sample_name
    .span-3
      =f.label :adn_type
    .span-2
      =f.label :capilar_type
    .span-5
      =f.label :oligo
    .span-2.last
      &nbsp

  .span-24.tbl_det
    - i=0
    - l = @sequence_request.sequence_request_details.length-1
    =f.fields_for :sequence_request_details do |srd|
      =render :partial => 'new_sequence_request_detail', :locals => {:srd => srd, :idx => i, :lst => l}
      - i +=1

  .span-19.last &nbsp
  .actions
    = f.submit  t(".submit"), :class => 'jq-button'

app/views/sequence_requests/_new_sequence_request_detail.html (copy).haml
.sample
  .span-12
    =srd.text_field :sample_name, :style => "width: 465px;"
  .span-3
    =srd.select :adn_type_id, SequenceRequestDetail::ADN_TYPE_OPTIONS, {},:style => "width: 110px;"
  .span-2
    =srd.select :capilar, SequenceRequestDetail::CAPILAR_TYPE, {},:style => "width: 70px;"
  .span-5
    = select_tag "oligo_sel#{[idx]}", options_for_select(SequenceRequestDetail::OLIGO_OPTIONS, @sequence_request.sequence_request_details[idx].oligo_id), {:include_blank => '', :style => "width: 78px;", :class => 'oligo_sel'}
    = srd.text_field :oligo_id, :style => "width: 104px;"
  .span-1
    //remove link if it is not the first
    -if idx > 0
      = link_to '-', nil , :remote => true, :id => "remove_sequence_request_detail",  :class=> "remove_sequence_request_detail jq-icon-minus"

  .span-1.last
    //add link if it is the last
    -if lst==idx
      = link_to '+', add_sequence_request_detail_path(:i => idx, :sequence_request => '3') , :remote => true, :id => "add_sequence_request_detail",  :class=> "add_sequence_request_detail jq-icon-plus"

app/views/sequence_requests/_new_sequence_request_detail.html.haml
.sample
  .span-12
    =srd.text_field :sample_name, :style => "width: 465px;"
  .span-3
    =srd.select :adn_type_id, SequenceRequestDetail::ADN_TYPE_OPTIONS, {},:style => "width: 110px;"
  .span-2
    =srd.select :capilar, SequenceRequestDetail::CAPILAR_TYPE, {},:style => "width: 70px;"
  .span-5
    = select_tag "oligo_sel#{[idx]}", options_for_select(SequenceRequestDetail::OLIGO_OPTIONS, @sequence_request.sequence_request_details[idx].oligo_id), {:include_blank => '', :style => "width: 78px;", :class => 'oligo_sel'}
    = srd.text_field :oligo_id, :style => "width: 104px;"
  .span-1
    //remove link if it is not the first
    -if idx > 0
      = link_to '-', nil , :remote => true, :id => "remove_sequence_request_detail",  :class=> "remove_sequence_request_detail jq-icon-minus"

  .span-1.last
    //add link if it is the last
    -if lst==idx
      = link_to '+', add_sequence_request_detail_path(:i => idx, :sequence_request => '3') , :remote => true, :id => "add_sequence_request_detail",  :class=> "add_sequence_request_detail jq-icon-plus"

app/views/sequence_requests/_new_sequence_request_detail_ajax.html (copy).haml
.sample
  .span-12
    = text_field "sequence_request[sequence_request_details_attributes][#{idx}]", 'sample_name', :style => "width: 465px;"
  .span-3
    = select "sequence_request[sequence_request_details_attributes][#{idx}]", :adn_type_id, SequenceRequestDetail::ADN_TYPE_OPTIONS,{}, :style => "width: 110px;"
  .span-2
    =select "sequence_request[sequence_request_details_attributes][#{idx}]", :capilar, SequenceRequestDetail::CAPILAR_TYPE, {},:style => "width: 70px;"
  .span-5
    //= select :oligo_sel, :oligo_sel, options_for_select(SequenceRequestDetail::OLIGO_OPTIONS), {}, {:include_blank => '', :style => "width: 78px;"}
    = select_tag "oligo_sel#{[idx]}", options_for_select(SequenceRequestDetail::OLIGO_OPTIONS), {:include_blank => '', :style => "width: 78px;", :class => 'oligo_sel'}
    = text_field "sequence_request[sequence_request_details_attributes][#{idx}]", :oligo_id, :style => "width: 104px;"
  .span-1
    //remove link if it is not the first
    = link_to '-', ' ' , :remote => true, :id => "remove_sequence_request_detail",  :class=> "remove_sequence_request_detail jq-icon-minus"

  .span-1.last
    //add link if it is the last
    = link_to '+', add_sequence_request_detail_path(:i => idx, :sequence_request => 'sequence_request') , :remote => true, :id => "add_sequence_request_detail",  :class=> "add_sequence_request_detail jq-icon-plus"

app/views/sequence_requests/_new_sequence_request_detail_ajax.html.haml
.sample
  .span-12
    = text_field "sequence_request[sequence_request_details_attributes][#{idx}]", 'sample_name', :style => "width: 465px;"
  .span-3
    = select "sequence_request[sequence_request_details_attributes][#{idx}]", :adn_type_id, SequenceRequestDetail::ADN_TYPE_OPTIONS,{}, :style => "width: 110px;"
  .span-2
    =select "sequence_request[sequence_request_details_attributes][#{idx}]", :capilar, SequenceRequestDetail::CAPILAR_TYPE, {},:style => "width: 70px;"
  .span-5
    //= select :oligo_sel, :oligo_sel, options_for_select(SequenceRequestDetail::OLIGO_OPTIONS), {}, {:include_blank => '', :style => "width: 78px;"}
    = select_tag "oligo_sel#{[idx]}", options_for_select(SequenceRequestDetail::OLIGO_OPTIONS), {:include_blank => '', :style => "width: 78px;", :class => 'oligo_sel'}
    = text_field "sequence_request[sequence_request_details_attributes][#{idx}]", :oligo_id, :style => "width: 104px;"
  .span-1
    //remove link if it is not the first
    = link_to '-', ' ' , :remote => true, :id => "remove_sequence_request_detail",  :class=> "remove_sequence_request_detail jq-icon-minus"

  .span-1.last
    //add link if it is the last
    = link_to '+', add_sequence_request_detail_path(:i => idx, :sequence_request => 'sequence_request') , :remote => true, :id => "add_sequence_request_detail",  :class=> "add_sequence_request_detail jq-icon-plus"

app/views/sequence_requests/add_sequence_request_detail.js.erb
/**
 * Created by JetBrains RubyMine.
 * User: martinezo
 * Date: 8/18/11
 * Time: 7:46 AM
 * To change this template use File | Settings | File Templates.
 */


/* $("#add_new_detail").remove() */
$(".tbl_det").append("<%= escape_javascript(render :partial => 'new_sequence_request_detail_ajax', :locals => {:idx => params[:i].to_i+1}) %>")
activate_jq_icons();

app/views/sequence_requests/edit.html.haml
%h1 Editing sequence_request
= render 'form'
= link_to 'Show', @sequence_request
|
\#{link_to 'Back', sequence_requests_path}

app/views/sequence_requests/index.html.haml
%h1 Listing sequence_requests
%table
  %tr
    %th Company
    %th Petitioner
    %th Email
    %th Phone
    %th Group leader
    %th Payment method
    %th
    %th
    %th
  - @sequence_requests.each do |sequence_request|
    %tr
      %td= sequence_request.company
      %td= sequence_request.petitioner
      %td= sequence_request.email
      %td= sequence_request.phone
      %td= sequence_request.group_leader
      %td= sequence_request.payment_method
      %td= link_to 'Show', sequence_request
      %td= link_to 'Edit', edit_sequence_request_path(sequence_request)
      %td= link_to 'Destroy', sequence_request, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Sequence request', new_sequence_request_path

app/views/sequence_requests/new.html.haml
%br/
.span-19.last
  %h1= t('sequence_request.sequence_request')
  = render 'form'

app/views/sequence_requests/sent.html.haml
%h1
  %Strong Solicitud de secuencias de ácidos nucleicos

%br/
%br/

%h2
  %Strong= params[:notice]

%br/
%br/

= link_to 'Decargar el formulario de solicitud/pago', sequence_request_download_file_path(:file_name => params[:file_name]), :class => 'jq-button'
= link_to 'Terminar', new_sequence_request_path, :class => 'jq-button'

app/views/sequence_requests/show.html.haml
%p#notice= notice
%p
  %b Company:
  = @sequence_request.company
%p
  %b Petitioner:
  = @sequence_request.petitioner
%p
  %b Email:
  = @sequence_request.email
%p
  %b Phone:
  = @sequence_request.phone
%p
  %b Group leader:
  = @sequence_request.group_leader
%p
  %b Payment method:
  = @sequence_request.payment_method
= link_to 'Edit', edit_sequence_request_path(@sequence_request)
|
\#{link_to 'Back', sequence_requests_path}