config/routes.rb
UpgSequences::Application.routes.draw do
  namespace :admin do
    match 'login', :to => 'user_sessions#new', :as => 'login'
    match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
    match 'paid_unpaid/:id', :to => 'sequence_requests#paid_unpaid', :as => 'paid_unpaid'
    match 'cancel/:id', :to => 'sequence_requests#cancel', :as => 'cancel'
    match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
    match 'download_file', :to => 'sequence_requests#download_file', :as => 'download_file'
    match 'send_results/:id', :to => 'sequence_requests#send_results', :as => 'send_results'
    match 'generate_and_download_xls', :to => 'sequence_requests#generate_and_download_xls', :as => 'generate_and_download_xls'
    match 'reports_by_ur', :to => 'sequence_requests#reports_by_ur', :as => 'reports_by_ur'
    post 'generate_reports_by_ur', :to => 'sequence_requests#generate_reports_by_ur', :as => 'generate_reports_by_ur'
    post 'search_by_folio', :to => 'sequence_requests#search_by_folio', :as => 'search_by_folio'
    resources :user_sessions, :users, :sequence_requests,:prices
  end

  resources :sequence_requests

  match 'add_sequence_request_detail', :to => 'sequence_requests#add_sequence_request_detail', :as => 'add_sequence_request_detail'
  match 'sequence_request_sent', :to => 'sequence_requests#sent', :as => 'sequence_request_sent'
  match 'sequence_request_download_file', :to => 'sequence_requests#download_file', :as => 'sequence_request_download_file'

  root :to => "sequence_requests#new"

end

app/views/layouts/__error_messages.html.haml
%h2
  = "#{resource.errors.count} #{t(:error)} #{message}"
%ul
  - resource.errors.full_messages.each do |msg|
    %li= msg

app/views/layouts/_blueprint_css.html.haml
= stylesheet_link_tag 'sass/blueprint/screen', :media => 'screen, projection'
= stylesheet_link_tag 'sass/blueprint/print', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'sass/blueprint/ie', :media => 'screen, projection'

app/views/layouts/_left_menu.html.haml
%br/
%br/
-if params[:controller] == 'admin/sequence_requests'
  = link_to image_tag('solicitudes_on.gif'),  admin_sequence_requests_path
-else
  = link_to image_tag('solicitudes_off.gif'),  admin_sequence_requests_path
-if params[:controller] == 'admin/prices'
  = link_to image_tag('precios_on.gif'),  admin_prices_path
-else
  = link_to image_tag('precios_off.gif'),  admin_prices_path
-if params[:controller] == 'admin/users'
  = link_to image_tag('usuarios_on.gif'),  admin_users_path
-else
  = link_to image_tag('usuarios_off.gif'),  admin_users_path

= link_to image_tag('logout.jpg'),  admin_logout_path

app/views/layouts/app.html.haml
!!!
%html
  %head
    %title Unidad de Proteogenómica
    = stylesheet_link_tag('reset.css')
    = stylesheet_link_tag('blueprint/ie.css')
    = stylesheet_link_tag('blueprint/screen.css')
    = stylesheet_link_tag('layout.css')
    = stylesheet_link_tag('app.css')
    = stylesheet_link_tag('scaffold.css')
    = stylesheet_link_tag('jquery_ui/jquery-ui-1.8.16.custom.css')
    = stylesheet_link_tag('tiptipv13/tipTip.css')

    = javascript_include_tag('jquery-1.6.2.min.js')
    = javascript_include_tag('rails.js')
    = javascript_include_tag('app.js')
    = javascript_include_tag('jquery-ui-1.8.16.custom.min.js')
    = javascript_include_tag('tiptipv13/jquery.tipTip.minified.js')
    = csrf_meta_tag
  %body
    .container
      .span-24.last#header1
      .span-24.last#header2
      .span-24.last#content
        .span-5
          = render :partial => 'layouts/left_menu'
        .span-19.last= yield
      .span-24.last#footer
        %br/
        <p>diseño web Ramón Martínez Olvera | Instituto de Neurobiología UNAM<p>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "http://fonts.googleapis.com/css?family=Ubuntu:400,700,500", :rel => "stylesheet", :type => "text/css"}
    %title Unidad de Proteogenómica
    = render :partial => 'layouts/blueprint_css'
    = stylesheet_link_tag 'sass/application'
    = stylesheet_link_tag 'sass/layout'

    = javascript_include_tag('jquery-1.7.2.min.js')
    = javascript_include_tag('jquery-ui-1.8.21.custom.min.js')
    = javascript_include_tag('rails.js')
    = javascript_include_tag('application.js')
    = javascript_include_tag('app.js')
    -#= javascript_include_tag('tiptipv13/jquery.tipTip.minified.js')

    = csrf_meta_tags

  %body
    .container
      .span-24.last#header1
      .span-24.last#header2
      .span-24.last#content
        -if params[:controller] == 'sequence_requests' or params[:controller] ==  'admin/user_sessions'
          = yield
        -else
          .span-5
            = render :partial => 'layouts/left_menu'
          .span-19.last= yield
      .span-24.last#footer
        %br/
        diseño y desarrollo del la aplicación: Ramón Martínez Olvera /Instituto de Neurobiología de la UNAM